version: '3'

services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
        - PMA_ARBITRARY=1
        restart: always
        ports:
        - 8080:80
        volumes:
        - /sessions
        environment:
            PMA_HOST: root
            MYSQL_ROOT_PASSWORD: password

networks:
    default:
        external:
            name: mysql_default